cron:
  first_execute_all: true
  execute_achieve_etl: false
  # seconds
  job_actual_time: 3600

  etl:
    - name: ETL_GET_DATA_FROM_CUBE
      enabled: true
      cron: "30 21 * * *"
      critical: false
    - name: ETL_GET_DATA_FROM_JIRA_CSV
      enabled: true
      cron: "45 21 * * *"
      critical: false
    - name: ETL_GET_DATA_FROM_GTABLE
      enabled: true
      cron: "*/10 * * * *"
      critical: false
    - name: ETL_GET_START_TG_BOT
      enabled: false
      cron: "30 9 * * *"
      critical: false

  intervals:
    Ежедневно: "0 0 * * 1-5"
    Еженедельно: "0 0 * * 6"
    Ежемесячно: "0 0 1 * *"
    Ежеквартально: "0 0 1 3,6,9,12 *"
    Ежегодно: "0 0 29 12 *"

conf:
  google_table:
    max_retries: 3
    service_key: ./configs/service_account-${ENV}.json
    name: Gamification ${ENV}
    sheets:
      - name: Achievements-${ENV}
        target_table: achievements
      - name: Manual-${ENV}
        target_table: pers_achieve
      - name: Project SLA-${ENV}
        target_table: project_sla

telegram:
  grafana_url:
  response_link:

cube:
  separator: "~"

  sftp_host:
  sftp_port: 22
  sftp_filepath:
  sftp_archive_path:

  all_files_upload: false

  tables:
    - table_name: user
      file_name: users
      merge_cols:
        - login
      mapper_name: CUBE_USERS

    - table_name: user_timelog
      file_name: user_timelog
      merge_cols:
        - user_name
        - log_date
        - issue_id
        - time_worked_days
      mapper_name: CUBE_USER_TIMELOG

    - table_name: work_calendar
      file_name: work_calendar
      merge_cols:
        - user_name
        - log_date
      mapper_name: CUBE_WORK_CALENDAR


jira:
  archive_interval:
    issue: 365
    score: 10

  teams:
    - "Команда MM.SUP"

  csv_url:
  jql:
    general: jqlQuery=updated+%3E%3D+-3d+AND+project+not+in+%28ACRMCLONE%29+AND+assignee+in+
    clone: jqlQuery=updated+%3E%3D+-3d+AND+project+in+%28ACRMCLONE%29+AND+assignee+in+


prometheus:
  nodeExporterPort: 8000

database:
  merge_batch_size: 50

logging:
  path: logs/scheduler.log
  backupCount: 5
  maxMegaBytes: 100
  loggers:
    - name: scheduler
      lvl: DEBUG
    - name: etl
      lvl: DEBUG
    - name: database
      lvl: DEBUG

  #library
    - name: apscheduler
      lvl: ERROR
    - name: sqlalchemy
      lvl: ERROR