cron:
  first_execute_all: false
  execute_achieve_etl: true
  job_actual_time: 30

  etl:
    - name: ETL_GET_DATA_FROM_CUBE
      enabled: false
      cron: 30 21 * * *
      critical: false
    - name: ETL_GET_DATA_FROM_JIRA_CSV
      enabled: false
      cron: 45 21 * * *
      critical: true
    - name: ETL_GET_DATA_FROM_GTABLE
      enabled: false
      cron: "*/10 * * * *"
      critical: true
    - name: ETL_GET_START_TG_BOT
      enabled: false
      cron: "30 9 * * *"
      critical: false

  intervals:
    Ежедневно: "0 0 * * 1-5"
    Еженедельно: "0 0 * * 6"
    Ежемесячно: "0 0 1 * *"
    Ежеквартально: "0 0 1 3,6,9,12 *"
    Ежегодно: "0 0 29 12 *"

google_table:
  service_key: ./configs/service_account.json
  table_name: <Table name>
  achieve_sheet: Achievements
  personal_achieve_sheet: Manual


telegram:
  grafana_url: 'url'
  response_link: '<url>'

cube:
  csv_store_path: 'ETL/ETL_GET_DATA_FROM_CUBE/cube_export'
  drop_csv_column:
    - Unknown
    - Nan
    - Не указан сотрудник
    - Не указано
    - NULL

  tables:
    - table_name: cube_users
      csv_name: users
      merge_cols:
        - user_key
      mapper_name: CUBE_COLS_USERS

    - table_name: cube_user_timelog
      csv_name: user_timelog
      merge_cols:
        - user_name
        - log_date
        - issue_id
        - time_worked_days
      mapper_name: CUBE_COLS_USER_TIMELOG

    - table_name: cube_work_calendar
      csv_name: work_calendar
      merge_cols:
        - user_name
        - log_date
      mapper_name: CUBE_COLS_WORK_CALENDAR


jira:
  archive_interval:
    issue: 365
    score: 10

  teams:
    - "Команда MM.SUP"

  csv_url: <jira csv export url>
  jql:
    general: jqlQuery=updated+%3E%3D+-3d+AND+project+not+in+%28ACRMCLONE%29+AND+assignee+in+
    clone: jqlQuery=updated+%3E%3D+-3d+AND+project+in+%28ACRMCLONE%29+AND+assignee+in+

  micropulls:
    - name: OneTeam
      members:
        - andrey.pervushin
    - name: OtherTeam
      members:
        - andrey.pervushin

prometheus:
  nodeExporterPort: 8000

logging:
  path: logs/scheduler.log
  backupCount: 5
  maxMegaBytes: 100
  loggers:
    - name: ETL_GET_DATA_FROM_JIRA_CSV
      lvl: DEBUG
    - name: ETL_GET_DATA_FROM_CUBE
      lvl: DEBUG
    - name: ETL_GET_DATA_FROM_GTABLE
      lvl: DEBUG
    - name: scheduler
      lvl: DEBUG
    - name: apscheduler
      lvl: ERROR
    - name: sqlalchemy
      lvl: ERROR
