{
 "title": "Gamification dev",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Statuses",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "achieve_status_metric", "legendFormat": "{{describe}}" },
    { "expr": "etl_status_metric", "legendFormat": "{{describe}}" }
   ]
  },
  {
   "title": "Лог ошибок",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "achieve_error_metric_total",
     "legendFormat": "{{ index $labels \"name\" }} {{ index $labels \"describe\" }} "
    },
    {
     "expr": "etl_error_metric_total",
     "legendFormat": "{{ index $labels \"name\" }} "
    }
   ]
  },
  { "title": "Duration of tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "ETL and Achieve duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(etl_time_metrics_sum[$__rate_interval])",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "rate(achieve_time_metrics_sum{}[$__rate_interval])",
     "legendFormat": "{{describe}}"
    }
   ]
  },
  { "title": "SQL requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "SQL request",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum (rate(sqlalchemy_metrics_sum{}[$__rate_interval]) )without () > 0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Полный sql запрос",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sqlalchemy_metrics_created",
     "legendFormat": "{{ index $labels \"name\" }} {{ index $labels \"describe\" }} "
    }
   ]
  },
  { "title": "Python metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Connections pool",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(postgres_pool_active_connections)",
     "legendFormat": "active"
    },
    {
     "expr": "sum(postgres_pool_idle_connections)",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(postgres_pool_total_connections)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(postgres_detached_connections)",
     "legendFormat": "detached"
    }
   ]
  },
  {
   "title": "Garbage collector",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total{}[$__rate_interval])",
     "legendFormat": "collected - generation {{generation}}"
    },
    {
     "expr": "rate(python_gc_objects_uncollectable_total{}[$__rate_interval])",
     "legendFormat": "uncollected - generation {{generation}}"
    }
   ]
  }
 ]
}